# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9.12.x
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Build
        run: pnpm run build
        env:
          VITE_PRIVY_APP_ID: ${{ secrets.VITE_PRIVY_APP_ID }}
          VITE_STRIPE_PUBLIC_KEY: ${{ secrets.VITE_STRIPE_PUBLIC_KEY }}
          VITE_UMAMI_API_CLIENT_SECRET: ${{ secrets.VITE_UMAMI_API_CLIENT_SECRET }}
          VITE_UMAMI_API_CLIENT_USER_ID: ${{ secrets.VITE_UMAMI_API_CLIENT_USER_ID }}
          VITE_API_URL: ${{ vars.VITE_API_URL }}
          VITE_BACKEND_PROD_URL: ${{ vars.VITE_BACKEND_PROD_URL }}
          VITE_FRONTEND_PROD_URL: ${{ vars.VITE_FRONTEND_PROD_URL }}
          VITE_STRIPE_PRICE_ID: ${{ vars.VITE_STRIPE_PRICE_ID }}
          VITE_STRIPE_DONATION_PRODUCT_ID: ${{ vars.VITE_STRIPE_DONATION_PRODUCT_ID }}
          VITE_UMAMI_API_ORIGIN: ${{ vars.VITE_UMAMI_API_ORIGIN }}
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: "./dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4